services:
  next:
    build:
      context: .
      args:
        - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
        - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
        - NEXT_PUBLIC_DIRECTUS_URL=${NEXT_PUBLIC_DIRECTUS_URL}
        - NEXT_PUBLIC_APP_VERSION=test-e2e
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=production

  backend:
    image: ghcr.io/laurimaila/backend-personal-website:latest
    ports:
      - '3000:8080'
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - CORS_ORIGINS=${CORS_ORIGINS}
      - CONNECTION_STRING=Host=db;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - PHYSICS_SVC_URL=${PHYSICS_SVC_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_EXPIRY_HOURS=${JWT_EXPIRY_HOURS}
    depends_on:
      migration-svc:
        condition: service_completed_successfully

  physics-svc:
    image: ghcr.io/laurimaila/physics-svc:latest

  migration-svc:
    image: ghcr.io/laurimaila/liquibase-svc:latest
    environment:
      - JDBC_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:18-alpine
    volumes: # Store data in a named docker volume
      - personal-website-data-e2e:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  personal-website-data-e2e:
# docker compose --env-file .env.e2e -f compose.e2e.yaml up --build --force-recreate -d
# docker compose --env-file .env.e2e -f compose.e2e.yaml down -v
