apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: backend
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: frontend-src
  path: ./deploy/backend
  prune: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: backend-secrets
        optional: false
