apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: frontend
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: frontend-src
  path: ./deploy/frontend
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: frontend-config
        optional: true
      - kind: Secret
        name: frontend-secrets
        optional: false
