apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: frontend-src
  namespace: flux-system
spec:
  interval: 1m0s
  url: "ssh://git@github.com/laurimaila/personal-website"
  ref:
    branch: main
  secretRef:
    name: flux-system
